#!/usr/bin/env node

// Wrapper for ./site command
// Redirects to ./prolibu site

const { spawn } = require('child_process');
const path = require('path');

const prolibuPath = path.join(__dirname, 'prolibu');
const args = ['site', ...process.argv.slice(2)];

const child = spawn(prolibuPath, args, {
  stdio: 'inherit',
  cwd: process.cwd()
});

child.on('exit', (code) => {
  process.exit(code);
});
